### ISSUE TITLE
how to change the gazebo environment model in the pick and place demo?

### ISSUE THREAD

**Issue by liusanchuan** [ROBOTIS-GIT/turtlebot3_manipulation#15]
how to change the gazebo environment model in the pick and place demo?
we are going to hold a competition similar to the pick and place demo，but the environment model need to be changed . i wonder how to modify your gazebo sdf file. can you suggest some app/software?

**Comment by JaehyunShim** [comment]
@liusanchuan 

Please refer to the links below.
(http://wiki.ros.org/simulator_gazebo/Tutorials)
(http://gazebosim.org/tutorials)

If your questions are about how to use ROS or Gazebo rather than how to use Turtlebot, please ask them at the link below.
(https://answers.ros.org/questions/)

If you have any other questions about the usage of our products, please open a new issue. 
Ryan
