### ISSUE TITLE
Lidar position not adjusted

### ISSUE THREAD

**Issue by Vitus012** [ROBOTIS-GIT/turtlebot3_manipulation#47]
Hi,
I am trying to use the TurtleBot3 with the OpenManipulator-X in ROS2.
I wanted to see the difference in position of the lidar scanner, when mounting the OpenManipulator, since it has to be moved forward.
But the urdf-files from the original TurtleBot3 package use the same offset.

Also, I am not sure how to align the lidar scanner properly, when moving it. Normally the disc is at the center, but no new reference is given.

**Comment by sunghowoo** [comment]
To adjust the position of the LiDAR scanner when mounting the OpenManipulator-X, you will need to manually update the URDF file to reflect the new offset. You can modify the origin tag for the LiDAR link in the URDF to move it forward. Be sure to align the scanner by adjusting the position and orientation values so that the disc remains centered after moving it. Unfortunately, no automatic reference is provided, so it may require some trial and error to get the alignment correct. I will close this issue as it has been open for too long.
