### ISSUE TITLE
compile for Noetic on 20.04 Ubuntu

### ISSUE THREAD

**Issue by MikeHallettUK** [ROBOTIS-GIT/turtlebot3_manipulation#49]
I tried to compile for Noetic on 20.04 Ubuntu: failed with error could not find "liboctomap.so.1.9.8".

I have liboctomap.so.1.9.7 ...
I already have a mature TB3 setup on Noetic, and have open_manipulator compiled and running ok.

Any advice please ?

Thanks

Mike

**Comment by sunghowoo** [comment]
It seems like the issue arises from a version mismatch of the `liboctomap` library. Your system has `liboctomap.so.1.9.7`, but the build is looking for version 1.9.8. First, try updating to the latest version. Apologies for the delayed response. Since this issue has been open for too long, I will go ahead and close it.
